baseURL: "https://mhbxyz.github.io/"
languageCode: "fr"
title: "mhbxyz"
theme: "PaperMod"
defaultContentLanguage: "fr"
defaultContentLanguageInSubdir: true
math: true

params:
  math: true

languages:
  fr:
    languageName: "Français"
    weight: 1
    contentDir: "content/fr"
    title: "[ mhbxyz / fr ]"
    menu:
      main:
        - name: "Accueil"
          url: "/fr/"
          weight: 1
        - name: "Essais"
          url: "/fr/essais/"
          weight: 2
        - name: "Articles"
          url: "/fr/articles/"
          weight: 3
    params:
      ShowReadingTime: true
      ShowShareButtons: false
      disableSpecial1stPost: true
      math: true
      profileMode:
        enabled: true
        title: "L'Ultime Rébellion"
        subtitle: '"Celui qui est mort au monde n’est plus troublé par ses malheurs."'
        imageUrl: "https://avatars.githubusercontent.com/u/43188009?v=4"
        imageTitle: "Death To The World!"
        imageWidth: 256
        imageHeight: 256

  en:
    languageName: "English"
    weight: 2
    contentDir: "content/en"
    title: "[ mhbxyz / en ]"
    menu:
      main:
        - name: "Home"
          url: "/en/"
          weight: 1
        - name: "Essays"
          url: "/en/essays/"
          weight: 2
        - name: "Articles"
          url: "/en/articles/"
          weight: 3
    params:
      ShowReadingTime: true
      ShowShareButtons: false
      disableSpecial1stPost: true
      math: true
      profileMode:
        enabled: true
        title: "The Last Rebellion"
        subtitle: '"He who is dead to the world is no longer disturbed by its woes."'
        imageUrl: "https://avatars.githubusercontent.com/u/43188009?v=4"
        imageTitle: "Death To The World!"
        imageWidth: 256
        imageHeight: 256
